new Vue({
    el:"#app",
    data:{
        datas:[
            {
                id:1,
                title:"11111",
            },
            {
                id:2,
                title:"22222",
            },
            {
                id:3,
                title:"33333",
            }
        ],
        status:false,
        title:''
    },
    methods:{
        focuss(){
            this.status=true;
        },
        changes(val){
            this.title=val;
            this.status=false;
        }
    }
})